package models;
// Generated 04-ene-2020 1:44:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	private int idGrupo;
	private String nombre;
	private Set alumnos = new HashSet(0);

	public Grupo() {
	}

	public Grupo(int idGrupo, String nombre) {
		this.idGrupo = idGrupo;
		this.nombre = nombre;
	}

	public Grupo(int idGrupo, String nombre, Set alumnos) {
		this.idGrupo = idGrupo;
		this.nombre = nombre;
		this.alumnos = alumnos;
	}

	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

}
