package objetos;
// Generated 12-ene-2020 20:14:37 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pasajero generated by hbm2java
 */
public class Pasajero implements java.io.Serializable {

	private short cod;
	private String nombre;
	private String tlf;
	private String direccion;
	private String pais;
	private Set pasajes = new HashSet(0);

	public Pasajero() {
	}

	public Pasajero(short cod) {
		this.cod = cod;
	}

	public Pasajero(short cod, String nombre, String tlf, String direccion, String pais, Set pasajes) {
		this.cod = cod;
		this.nombre = nombre;
		this.tlf = tlf;
		this.direccion = direccion;
		this.pais = pais;
		this.pasajes = pasajes;
	}

	public short getCod() {
		return this.cod;
	}

	public void setCod(short cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getPasajes() {
		return this.pasajes;
	}

	public void setPasajes(Set pasajes) {
		this.pasajes = pasajes;
	}

}
