package objetos;
// Generated 12-ene-2020 20:14:37 by Hibernate Tools 5.4.7.Final

/**
 * TripulacionId generated by hbm2java
 */
public class TripulacionId implements java.io.Serializable {

	private String vueloIdentificador;
	private short personalCodigo;

	public TripulacionId() {
	}

	public TripulacionId(String vueloIdentificador, short personalCodigo) {
		this.vueloIdentificador = vueloIdentificador;
		this.personalCodigo = personalCodigo;
	}

	public String getVueloIdentificador() {
		return this.vueloIdentificador;
	}

	public void setVueloIdentificador(String vueloIdentificador) {
		this.vueloIdentificador = vueloIdentificador;
	}

	public short getPersonalCodigo() {
		return this.personalCodigo;
	}

	public void setPersonalCodigo(short personalCodigo) {
		this.personalCodigo = personalCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TripulacionId))
			return false;
		TripulacionId castOther = (TripulacionId) other;

		return ((this.getVueloIdentificador() == castOther.getVueloIdentificador())
				|| (this.getVueloIdentificador() != null && castOther.getVueloIdentificador() != null
						&& this.getVueloIdentificador().equals(castOther.getVueloIdentificador())))
				&& (this.getPersonalCodigo() == castOther.getPersonalCodigo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVueloIdentificador() == null ? 0 : this.getVueloIdentificador().hashCode());
		result = 37 * result + this.getPersonalCodigo();
		return result;
	}

}
