package objetos;
// Generated 12-ene-2020 20:14:37 by Hibernate Tools 5.4.7.Final

/**
 * Tripulacion generated by hbm2java
 */
public class Tripulacion implements java.io.Serializable {

	private TripulacionId id;
	private Personal personal;
	private Vuelo vuelo;
	private String puesto;

	public Tripulacion() {
	}

	public Tripulacion(TripulacionId id, Personal personal, Vuelo vuelo) {
		this.id = id;
		this.personal = personal;
		this.vuelo = vuelo;
	}

	public Tripulacion(TripulacionId id, Personal personal, Vuelo vuelo, String puesto) {
		this.id = id;
		this.personal = personal;
		this.vuelo = vuelo;
		this.puesto = puesto;
	}

	public TripulacionId getId() {
		return this.id;
	}

	public void setId(TripulacionId id) {
		this.id = id;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public Vuelo getVuelo() {
		return this.vuelo;
	}

	public void setVuelo(Vuelo vuelo) {
		this.vuelo = vuelo;
	}

	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

}
